name: 'github config'
description: 'Update GIT config with signing key'
inputs:
  gpg-key-base64:
    description: 'Base64 GPG key'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        mkdir -p ${GITHUB_WORKSPACE}/.gpg
        echo ${{ inputs.gpg-key-base64 }} | base64 -d > ${GITHUB_WORKSPACE}/.gpg/private.key
        gpg --import ${GITHUB_WORKSPACE}/.gpg/private.key

        git config --global user.signingkey <user-signingkey>
        git config --global commit.gpgsign true
        git config user.name ci-macpaw
        git config user.email admin+ci-gh@macpaw.com
      shell: bash
      name: Update git config
