name: "Prepare Node"
description: "Sets up Node.js and runs install if it's needed"
inputs:
  node-version:
    description: 'The version of Node.js to use'
    required: true
  node-cache:
    description: 'The cache key to use for caching Node.js'
    required: false
  package-manager:
    description: 'The package manager to use'
    required: false
    default: 'npm'
  registry-url:
    description: 'The registry URL to use'
    required: false
  scope:
    description: 'The scope to use'
    required: false
    default: ''
  install-dependencies:
    description: 'Whether to install dependencies'
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Install pnpm
      if: ${{ inputs.package-manager == 'pnpm' }}
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 8
        run_install: false

    - name: Setup Node version
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.node-cache }}
        registry-url: ${{ inputs.registry-url }}
        scope: ${{ inputs.scope }}

    - name: Install dependencies
      shell: bash
      if: ${{ inputs.install-dependencies == 'true' }}
      run: ${{ inputs.package-manager }} install
