name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@macpaw'
      - run: yarn
      - run: npx @svgr/cli src/icons/svg --out-dir src/icons/jsx
      - run: npx eslint src/icons/jsx --fix
      - run: yarn lib:css
      - run: yarn lib:js
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}